import { describe, expect, it } from 'vitest';
import {
  buildPostgresCreateIndexStatement,
  buildPostgresCreateStatement,
  buildPostgresCreateTableStatement,
} from '@/services/drivers/postgres-structure';

describe('postgres-structure', () => {
  it('buildPostgresCreateTableStatement 应生成主键与 identity', () => {
    const sql = buildPostgresCreateTableStatement({
      tableName: 'users',
      columns: [
        { name: 'id', type: 'bigint', nullable: false, primaryKey: true, autoIncrement: true },
        { name: 'name', type: 'text', nullable: false, defaultExpression: "'guest'" },
      ],
    });

    expect(sql).toContain('CREATE TABLE "users"');
    expect(sql).toContain('"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(sql).toContain('PRIMARY KEY ("id")');
  });

  it('buildPostgresCreateIndexStatement 应生成唯一索引 SQL', () => {
    const sql = buildPostgresCreateIndexStatement('users', {
      name: 'idx_users_email',
      columns: ['email'],
      unique: true,
    });

    expect(sql).toBe('CREATE UNIQUE INDEX "idx_users_email" ON "users" ("email")');
  });

  it('buildPostgresCreateStatement 应拼接建表和索引 SQL', () => {
    const sql = buildPostgresCreateStatement(
      'users',
      [{ name: 'id', type: 'bigint', nullable: false, primaryKey: true, autoIncrement: true }],
      [
        { name: 'PRIMARY', columns: ['id'], unique: true, primary: true },
        { name: 'idx_users_created_at', columns: ['created_at'], unique: false, primary: false },
      ],
    );

    expect(sql).toContain('CREATE TABLE "users"');
    expect(sql).toContain('CREATE INDEX "idx_users_created_at" ON "users" ("created_at")');
  });
});
