import type {
  CreateTableRequest,
  TableStructureColumnInput,
  TableStructureIndex,
  TableStructureIndexInput,
} from '../../types';
import { assertValidCreateTableInput, normalizeDefinitionName, toSqlDefaultExpression } from './structure-shared';

export function quotePostgresIdentifier(name: string): string {
  return `"${name.replaceAll('"', '""')}"`;
}

function buildPostgresColumnDefinition(column: TableStructureColumnInput): string {
  const name = normalizeDefinitionName(column.name, '列名');
  const type = normalizeDefinitionName(column.type, '列类型');
  const parts = [quotePostgresIdentifier(name), type];

  if (column.autoIncrement) {
    parts.push('GENERATED BY DEFAULT AS IDENTITY');
  }

  if (column.primaryKey || !column.nullable) {
    parts.push('NOT NULL');
  }

  const defaultExpression = toSqlDefaultExpression(column.defaultExpression);
  if (defaultExpression !== null && !column.autoIncrement) {
    parts.push(`DEFAULT ${defaultExpression}`);
  }

  return parts.join(' ');
}

export function buildPostgresAddColumnStatement(tableName: string, column: TableStructureColumnInput): string {
  if (column.primaryKey) {
    throw new Error('当前版本暂不支持在现有 PostgreSQL 表中新增主键列');
  }

  if (column.autoIncrement) {
    throw new Error('当前版本暂不支持在现有 PostgreSQL 表中新增自增列');
  }

  return `ALTER TABLE ${quotePostgresIdentifier(tableName)} ADD COLUMN ${buildPostgresColumnDefinition(column)}`;
}

export function buildPostgresCreateTableStatement(input: CreateTableRequest): string {
  assertValidCreateTableInput(input);

  const primaryKeyColumns = input.columns.filter((column) => column.primaryKey);
  const definitions = input.columns.map(buildPostgresColumnDefinition);

  if (primaryKeyColumns.length > 0) {
    definitions.push(
      `PRIMARY KEY (${primaryKeyColumns.map((column) => quotePostgresIdentifier(column.name.trim())).join(', ')})`,
    );
  }

  return `CREATE TABLE ${quotePostgresIdentifier(input.tableName.trim())} (\n  ${definitions.join(',\n  ')}\n)`;
}

export function buildPostgresCreateIndexStatement(tableName: string, index: TableStructureIndexInput): string {
  const indexName = normalizeDefinitionName(index.name, '索引名');
  if (index.columns.length === 0) {
    throw new Error('索引至少需要一列');
  }

  const columnSql = index.columns
    .map((columnName) => quotePostgresIdentifier(normalizeDefinitionName(columnName, '列名')))
    .join(', ');
  const uniqueKeyword = index.unique ? 'UNIQUE ' : '';
  return `CREATE ${uniqueKeyword}INDEX ${quotePostgresIdentifier(indexName)} ON ${quotePostgresIdentifier(tableName)} (${columnSql})`;
}

export function buildPostgresCreateStatement(
  tableName: string,
  columns: TableStructureColumnInput[],
  indexes: TableStructureIndex[],
): string {
  const createTableSql = buildPostgresCreateTableStatement({
    tableName,
    columns,
  });
  const indexSql = indexes
    .filter((index) => !index.primary)
    .map((index) =>
      buildPostgresCreateIndexStatement(tableName, {
        name: index.name,
        columns: index.columns,
        unique: index.unique,
      }),
    );

  if (indexSql.length === 0) {
    return createTableSql;
  }

  return `${createTableSql};\n${indexSql.join(';\n')}`;
}
