import type { CreateTableRequest, SqlDialect, TableStructureColumnInput, TableStructureIndexInput } from '@/lib/api';

function quoteIdentifier(dialect: SqlDialect, name: string): string {
  if (dialect === 'mysql') {
    return `\`${name.replaceAll('`', '``')}\``;
  }

  return `"${name.replaceAll('"', '""')}"`;
}

function normalizeDefaultExpression(value: string | null | undefined): string | null {
  if (typeof value !== 'string') {
    return null;
  }

  const trimmed = value.trim();
  return trimmed ? trimmed : null;
}

function escapeSqlString(value: string): string {
  return value.replaceAll("'", "''");
}

function toSqlDefaultExpression(value: string | null | undefined): string | null {
  const normalized = normalizeDefaultExpression(value);
  if (!normalized) {
    return null;
  }

  if (/^'.*'$/s.test(normalized) || /^".*"$/s.test(normalized)) {
    return normalized;
  }

  if (/^[+-]?\d+(?:\.\d+)?$/.test(normalized)) {
    return normalized;
  }

  if (
    ['NULL', 'CURRENT_TIMESTAMP', 'CURRENT_DATE', 'CURRENT_TIME', 'NOW()', 'TRUE', 'FALSE'].includes(
      normalized.toUpperCase(),
    )
  ) {
    return normalized.toUpperCase();
  }

  if (/^[A-Za-z_][\w$]*\s*\([^)]*\)$/.test(normalized) || normalized.includes('::') || /^\(.+\)$/.test(normalized)) {
    return normalized;
  }

  return `'${escapeSqlString(normalized)}'`;
}

function buildColumnDefinition(
  dialect: SqlDialect,
  column: TableStructureColumnInput,
  inlinePrimaryKey: boolean,
): string {
  const name = quoteIdentifier(dialect, column.name.trim());
  const type = column.type.trim();
  const defaultExpression = toSqlDefaultExpression(column.defaultExpression);
  const parts = [name, type];
  const isPrimaryKey = Boolean(column.primaryKey);

  if (dialect === 'postgres') {
    if (column.autoIncrement) {
      parts.push('GENERATED BY DEFAULT AS IDENTITY');
    }

    if (isPrimaryKey || !column.nullable) {
      parts.push('NOT NULL');
    }

    if (defaultExpression !== null && !column.autoIncrement) {
      parts.push(`DEFAULT ${defaultExpression}`);
    }

    return parts.join(' ');
  }

  if (inlinePrimaryKey) {
    parts.push('PRIMARY KEY');
  }

  if (dialect === 'mysql') {
    parts.push(inlinePrimaryKey || isPrimaryKey || !column.nullable ? 'NOT NULL' : 'NULL');
    if (defaultExpression !== null && !column.autoIncrement) {
      parts.push(`DEFAULT ${defaultExpression}`);
    }
    if (column.autoIncrement) {
      parts.push('AUTO_INCREMENT');
    }
    return parts.join(' ');
  }

  if (column.autoIncrement) {
    parts.push('AUTOINCREMENT');
  }

  if (inlinePrimaryKey || isPrimaryKey || !column.nullable) {
    parts.push('NOT NULL');
  }

  if (defaultExpression !== null && !column.autoIncrement) {
    parts.push(`DEFAULT ${defaultExpression}`);
  }

  return parts.join(' ');
}

function buildIndexStatement(dialect: SqlDialect, tableName: string, index: TableStructureIndexInput): string {
  const uniqueKeyword = index.unique ? 'UNIQUE ' : '';
  const columnSql = index.columns.map((column) => quoteIdentifier(dialect, column.trim())).join(', ');
  return `CREATE ${uniqueKeyword}INDEX ${quoteIdentifier(dialect, index.name.trim())} ON ${quoteIdentifier(dialect, tableName.trim())} (${columnSql})`;
}

export function buildCreateTablePreview(dialect: SqlDialect, input: CreateTableRequest): string {
  const primaryColumns = input.columns.filter((column) => column.primaryKey);
  const inlinePrimaryKeyName = primaryColumns.length === 1 ? (primaryColumns[0]?.name.trim() ?? null) : null;
  const columnSql = input.columns.map((column) =>
    buildColumnDefinition(dialect, column, inlinePrimaryKeyName === column.name.trim()),
  );

  if (primaryColumns.length > 1) {
    columnSql.push(
      `PRIMARY KEY (${primaryColumns.map((column) => quoteIdentifier(dialect, column.name.trim())).join(', ')})`,
    );
  }

  const statements = [
    `CREATE TABLE ${quoteIdentifier(dialect, input.tableName.trim())} (\n  ${columnSql.join(',\n  ')}\n)`,
    ...(input.indexes || []).map((index) => buildIndexStatement(dialect, input.tableName, index)),
  ];

  return `${statements.join(';\n')};`;
}

export function buildCreateColumnPreview(
  dialect: SqlDialect,
  tableName: string,
  input: TableStructureColumnInput,
): string {
  return `ALTER TABLE ${quoteIdentifier(dialect, tableName)} ADD COLUMN ${buildColumnDefinition(
    dialect,
    input,
    Boolean(input.primaryKey),
  )};`;
}

export function buildUpdateColumnPreview(
  dialect: SqlDialect,
  tableName: string,
  currentColumnName: string,
  input: TableStructureColumnInput,
): string {
  if (dialect === 'mysql') {
    return `${[
      `ALTER TABLE ${quoteIdentifier(dialect, tableName)} CHANGE COLUMN ${quoteIdentifier(
        dialect,
        currentColumnName,
      )} ${buildColumnDefinition(dialect, input, Boolean(input.primaryKey))}`,
    ].join('\n')};`;
  }

  if (dialect === 'postgres') {
    const nextName = input.name.trim();
    const statements = [];

    if (nextName !== currentColumnName) {
      statements.push(
        `ALTER TABLE ${quoteIdentifier(dialect, tableName)} RENAME COLUMN ${quoteIdentifier(
          dialect,
          currentColumnName,
        )} TO ${quoteIdentifier(dialect, nextName)}`,
      );
    }

    statements.push(
      `ALTER TABLE ${quoteIdentifier(dialect, tableName)} ALTER COLUMN ${quoteIdentifier(
        dialect,
        nextName,
      )} TYPE ${input.type.trim()}`,
    );

    statements.push(
      `ALTER TABLE ${quoteIdentifier(dialect, tableName)} ALTER COLUMN ${quoteIdentifier(
        dialect,
        nextName,
      )} ${input.nullable ? 'DROP NOT NULL' : 'SET NOT NULL'}`,
    );

    const defaultExpression = toSqlDefaultExpression(input.defaultExpression);
    statements.push(
      defaultExpression === null
        ? `ALTER TABLE ${quoteIdentifier(dialect, tableName)} ALTER COLUMN ${quoteIdentifier(
            dialect,
            nextName,
          )} DROP DEFAULT`
        : `ALTER TABLE ${quoteIdentifier(dialect, tableName)} ALTER COLUMN ${quoteIdentifier(
            dialect,
            nextName,
          )} SET DEFAULT ${defaultExpression}`,
    );

    return `${statements.join(';\n')};`;
  }

  if (input.name.trim() !== currentColumnName) {
    return `${[
      `ALTER TABLE ${quoteIdentifier(dialect, tableName)} RENAME COLUMN ${quoteIdentifier(
        dialect,
        currentColumnName,
      )} TO ${quoteIdentifier(dialect, input.name.trim())}`,
      '-- SQLite 的其他列修改会通过重建表完成',
    ].join(';\n')};`;
  }

  return `${[
    '-- SQLite 会通过重建表来应用这次列修改',
    `-- 目标列定义：${buildColumnDefinition(dialect, input, Boolean(input.primaryKey))}`,
  ].join('\n')}`;
}

export function buildCreateIndexPreview(
  dialect: SqlDialect,
  tableName: string,
  index: TableStructureIndexInput,
): string {
  return `${buildIndexStatement(dialect, tableName, index)};`;
}

export function buildUpdateIndexPreview(
  dialect: SqlDialect,
  tableName: string,
  currentIndexName: string,
  index: TableStructureIndexInput,
): string {
  const dropStatement =
    dialect === 'mysql'
      ? `ALTER TABLE ${quoteIdentifier(dialect, tableName)} DROP INDEX ${quoteIdentifier(dialect, currentIndexName)}`
      : `DROP INDEX IF EXISTS ${quoteIdentifier(dialect, currentIndexName)}`;

  return `${[dropStatement, buildIndexStatement(dialect, tableName, index)].join(';\n')};`;
}
